### ISSUE TITLE
Create DB of initiatives that are springing up

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#1]
In GitLab by @rufuspollock on Apr 15, 2020, 18:19

See [Possibility Now - DB of Initiatives & Partners](https://docs.google.com/spreadsheets/d/1QJpTHWr9RKZGFaKjIR6itpQqQlGJNfXmoR8nFw-72EU/edit#gid=0)

## Tasks

* [x] jacques to add his
* [x] @shiweiart to add French initiatives to DB
* [x] @petronellatyson to add items to spreadsheet into DB

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 15, 2020, 18:26

unassigned @shiweiart

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 15, 2020, 18:26

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 18:36

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 18:36

@rufuspollock can you follow up with sylvie on whatsapp - i think she just has 2 examples ... and also ping petronella - maybe ping her on whatsapp with link to spreadsheet ...

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 18:57

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 19:15

assigned to @rufuspollock

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 17, 2020, 18:41

marked the task **@petronellatyson to add items to spreadsheet into DB** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 21, 2020, 19:04

marked the task **@shiweiart to add French initiatives to DB** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 21, 2020, 19:04

closed
