### ISSUE TITLE
[epic] Invitation and Sign on - First Round (first 20-30)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#13]
In GitLab by @rufuspollock on Apr 16, 2020, 18:23

We want to get 20 endorsers to check this works, test the process and establish and initial base.

## Acceptance

* [x] We have 20+ endorsers **We have 28+ as of 8 may**

## Tasks

* [x] Invitee drafts https://docs.google.com/document/d/1GYBqAJNBOhcLrsx8upsnFQS8sXyohSX0tRHoKffcSjQ/edit#heading=h.4p6hl5fgkus3
* [x] Each send at least 3 invitations
* [x] Keep going ...

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 18:31

assigned to @rufuspollock

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 8, 2020, 14:10

changed title from **[epic] Invitation and Sign on** to **[epic] Invitation and Sign on{+ - First Round (first 20-30)+}**

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 8, 2020, 14:10

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 8, 2020, 14:10

FIXED. We have 28+ endorsements.

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 8, 2020, 14:10

closed
