### ISSUE TITLE
[mvp] Website front page with declaration

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#2]
In GitLab by @rufuspollock on Apr 15, 2020, 18:25

Front page for possibility now with the declaration and some basic way to endorse (e.g. via email).

## Acceptance

* [x] Declaration
* [x] Theming
* [x] Basic endorse process (email)

## Tasks

* [x] Stub site with some kind of css framework (e.g. tailwind)
* [x] Declaration text with styling
* [x] Design of page
  * [x] Find inspirations
* [x] Implementation
* [x] Build and deploy **gitlab**

Implementing design

* [x] Simple, clean text (inspired by ia.net atm)
* [x] favicon with sunflower
* [x] "A initiative of Art / Earth / Tech"
* [x] Contributors
* [x] ~~Endorsers~~ **Later**

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 19, 2020, 09:40

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 19, 2020, 09:44

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 19, 2020, 09:44

marked the task **Find inspirations** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 19, 2020, 09:46

changed title from **{-Create Possibility Now front page-}** to **{+[mvp] Website front page with declaration+}**

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 21, 2020, 19:03

closed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 21, 2020, 19:03

marked the task **Simple, clean text (inspired by ia.net atm)** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 21, 2020, 19:03

marked the task **~~Endorsers~~ **Later**** as completed
