### ISSUE TITLE
[epic] MVP v1 (Declaration only)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#22]
In GitLab by @rufuspollock on Apr 17, 2020, 10:54

MVP v1 consists of the declaration and associated invite / signup / share processes.

* Declaration
* Website
* Trial invite (personally)
* Signup process
* Share process
* Go live

## Acceptance

* [x] Declaration of Possibility Now
* [x] Website with declaration
* [x] Feedback from 10 people
* [x] Sign up process for people in general
  * [ ] Shows number of endorsers and their name / link ...
* [ ] Share process (?)

## Tasks

* [x] Declaration
  * [x] Draft the manifesto #8
  * [x] Review manifesto
  * [x] Finalize
* [x] Manifesto website (single page for now) #22 
  * [x] Choose tool **static site using tailwind**
* [x] Endorse: Sign up flow
  * [x] Design overall flow esp sign up #18
  * [x] How do we do this? (can we use sendinblue, wordpress plugin?) **MVP = send us an email. see discussion below - for future work and analysis see #39**
* [ ] ~~Next action sign up flow e.g. creating groups~~ **FUTURE**

### Website

* [x] What are the options e.g. wordpress, headless content system, webflow, static site in html
* [x] Choose backend (just use wordpress.com?) => start with static then moved to vuepress
  * [x] does wordpress allow api access to blocks (o/w we are locked in) - no, not really you only get html
  * [x] what about prismic.io (how do you do previewing?) **Who knows, we did not try out**
  * [x] what about strapi **ditto - maybe for future**
  * [x] is there a better forestry **not afaict - there is netlify cms ...**

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 17, 2020, 11:07

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 17, 2020, 18:10

marked the task **Declaration** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 17, 2020, 18:10

marked the task **Review manifesto** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 17, 2020, 18:10

marked the task **Finalize** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 17, 2020, 18:40

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 17, 2020, 18:41

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 19, 2020, 09:46

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 19, 2020, 10:17

marked the task **Design overall flow esp sign up #18** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 17:16

marked the task **Declaration of Possibility Now** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 17:16

marked the task **Website with declaration** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 17:16

marked the task **Feedback from 10 people** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 17:41

marked the task **How do we do this? (can we use sendinblue, wordpress plugin?) **MVP = send us an email. see discussion below**** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 17:41

marked the task **Endorse: Sign up flow** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 17:42

marked the task **Sign up process for people in general** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 18:11

marked the task **What are the options e.g. wordpress, headless content system, webflow, static site in html** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 18:14

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 18:36

FIXED. It is working with email signup at https://possibilitynow.org

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 18:36

closed
