### ISSUE TITLE
Creating and managing the directory of initiatives

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#25]
In GitLab by @rufuspollock on Apr 21, 2020, 19:22

We want to have a directory of initiatives, organizations

An initiative is e.g. an invitation to submit proposals etc

## Acceptance

* [x] Have a spreadsheet with list that could be used to power a website **DONE: https://docs.google.com/spreadsheets/d/1QJpTHWr9RKZGFaKjIR6itpQqQlGJNfXmoR8nFw-72EU/edit#gid=281905530**
* [ ] Have a form we can embed in website for people to submit theirs

## Tasks

* [x] Create a sheet in a spreadsheet ...
* [ ] Create a form for people to submit to the directory

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 29, 2020, 18:34

@petronellatyson here's the task from week - for form I'd follow the structure we already have in https://docs.google.com/spreadsheets/d/1QJpTHWr9RKZGFaKjIR6itpQqQlGJNfXmoR8nFw-72EU/edit#gid=281905530

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 29, 2020, 18:35

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 4, 2020, 08:56

@petronellatyson got it. Are you now getting these notifications (can you make sure they don't go to spam?). And are you able to take this on?
