### ISSUE TITLE
Register a username on instagram and twitter

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#3]
In GitLab by @rufuspollock on Apr 15, 2020, 18:28

## Acceptance [Criteria]

* [x] Handle that will be used for Possibility Now is registered on twitter
* [x] Username that will be used for Possibility Now is registered on instagram
* [x] Registered with possibilitynow@artearthtech.com

## Tasks

* [x] register possibilitynow_ on twitter and instagram - **DONE**
* [x] register possibility_now in case we want this - **DONE**
* [x] fix possibilitynow@artearthtech.com not receiving emails from twitter/instagram

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 15, 2020, 19:05

changed title from **Register {-Possibility Now-} instagram and twitter** to **Register {+a username on+} instagram and twitter**

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 15, 2020, 19:06

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 18:16

I couldn't register possibilitynow, unsure if I should register other names

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 19:07

@rufuspollock is possibilitynow_ available - maybe a bit nicer ...

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 17, 2020, 11:17

marked the task **Handle that will be used for Possibility Now is registered on twitter** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 17, 2020, 11:17

marked the task **Username that will be used for Possibility Now is registered on instagram** as completed

**Comment by rufuspollock** [comment]
In GitLab by @petronellatyson on Apr 17, 2020, 18:08

I registered Possibility Now on Twitter last Sunday @PossibilityNow - the log in detail is in the Accounts and Usernames sheet

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 21, 2020, 12:04

marked the task **fix possibilitynow@artearthtech.com not receiving emails from twitter/instagram** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 21, 2020, 12:04

marked the task **Registered with possibilitynow@artearthtech.com** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 21, 2020, 12:11

Log in details for Instagram also in Accounts & Usernames sheet

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 21, 2020, 12:11

closed
