### ISSUE TITLE
[site] Share the declaration actions ...

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#38]
In GitLab by @rufuspollock on May 3, 2020, 17:44

Add a share this like at bottom of https://www.sustainablewebmanifesto.com/

## Acceptance

* [x] Share Possibility Now! with cool 'share' icon e.g. copy sustainable web!
  * alternative: "Share the Declaration"
* [x] share options to choose from e.g. share on twitter, per email.. 

![image](/uploads/aea9b54e3d897035fc9472a4fb371fd1/image.png)

## Tasks

* [x] build same section as on https://www.sustainablewebmanifesto.com/
* [x] improve it (colors, spacing, icons etc. if necessary)
* [x] make links work
  * [x] twitter 
    * [x] research how to add a link to a "ready to go" tweet --> https://twitter.com/intent/tweet?text=A+different+future+is+possible%21;url=https%3A%2F%2Fwww.possibilitynow.org
    * [x] apply
    * [x] test if it works
  * [x] research how to copy to clipboard in vue --> https://vuejsfeed.com/blog/copy-texts-to-clipboard-using-vue-clipboard2
  * [x] apply 
  * [x] test if it works
  * [x] set timeout to function so that the default text (a.k.a. "Copy to Clipboard") appears back
* [x] test if it works and if preview is ok
* [x] deploy

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 3, 2020, 17:49

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 3, 2020, 17:51

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 3, 2020, 17:51

assigned to @monikappv

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 18:05

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 18:06

changed time estimate to 1h

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 4, 2020, 13:38

marked the task **build same section as on https://www.sustainablewebmanifesto.com/** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 4, 2020, 13:38

marked the task **improve it (colors, spacing, icons etc. if necessary)** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 4, 2020, 13:38

marked the task **make links work** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 4, 2020, 13:59

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 4, 2020, 23:18

marked the task **test if it works and if preview is ok** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 4, 2020, 23:18

marked the task **deploy** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 4, 2020, 23:19

closed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 4, 2020, 23:19

marked the task **Share Possibility Now! with cool 'share' icon e.g. copy sustainable web!** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 4, 2020, 23:19

marked the task **share options to choose from e.g. share on twitter, per email..** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 6, 2020, 17:52

@monikappv well done and ...

* posting a screenshot of result in fixed is helpful (esp as it may change later) and allows me to review quicker
* you have put share this right at bottom of page and i think it would work better immediately at end of yellow section
  * on sustainable web the list of endorsers if on a separate page so share this is visible - in our setup it will quickly get lost
* **important** some indication that the action buttons are clickable - e.g. underlining or similar

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 7, 2020, 10:50

@rufuspollock FIXED.

* moved the share section code to a ShareThis.vue global component so its cleaner and easier to be placed on other pages if necessary
* changed the position to end of the yellow section
* added underline on links on hover
* screenshot below

![sharethisYellow](/uploads/fbb4dfea0005928edf521d4e9575cef4/sharethisYellow.png)

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 7, 2020, 16:08

done.

![sharesectionfixed](/uploads/94779ea397055639e4214696da0e0c03/sharesectionfixed.png)
