### ISSUE TITLE
[epic] Form endorse flow rather than email plus display total and names on website

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#39]
In GitLab by @rufuspollock on May 3, 2020, 18:09

We started in #22 with simple "send us an email" but that is poor UX, a bit unusual / unprofessional and we want to get specific info from people ... => let's move to a form ...

## Acceptance

* [x] People can sign up via a form
* [x] Display total
* [x] Display names and orgs (if happy to be public)

## Tasks

* [x] Sign up form working
* [x] Use data from form to show list of endorsers etc
* [x] Document this for others

### Form working 

* [x] choose the form system
  * [x] What are our needs?
  * [x] Research options
  * [x] Choose one and try it
    * [x] sendinblue :heavy_check_mark: 
    * [x] sendingrid
* [x] Embed form in site
* [x] Test it works e.g. submit and see what you get
* [x] Customize confirmation email you get (if there is one) --> no confirmation email
* [x] Deploy
* [x] improve form (translate to vue.js and embed as a component instead of using iframe)
* [x] improve confirmation page

### Total number and names 

* [x] write a node.js file that
  * [x] gets the endorsers data from sendinblue API
  * [x] gets the endorsers number
  * [x] saves the data into a local json file
* [x] create an Endorsers.vue component that displays the data in a nice layout like on https://www.sustainablewebmanifesto.com/signatures/
* [x] make sure it displays only people that want their names to be shown on site
* [x] embed Endorsers.vue on home page
* [x] test if it updates when script runs 
* [x] replace token with variable
* [x] place variable and token into enc file

### Showing the counts and public endorsers

Here's the API to get all the contacts for a list:

https://github.com/sendinblue/APIv3-nodejs-library/blob/master/docs/ContactsApi.md#getContactsFromList

And all contacts:

https://github.com/sendinblue/APIv3-nodejs-library/blob/master/docs/ContactsApi.md#getContacts

The simplest is to run this every so often as a script and save results to a local JSON (or CSV) file in the repo and then use that to render the page. We would just pull people who have given permission to be public and write their name and affiliation.

---

### MVP for endorse sign up

See https://hackmd.io/YQENBa0ATjya0B2bxiEH9Q

* nothing (or email us!)
  * Issues: manual, people might not write back etc
* => a form
  * Options: google form (ugly)[^maybe-not] / formspree
  * we can have opt-in to show name
  * we can capture org etc
  * Issues: no email confirmation means it could be spammed etc (or someone signs someone else up)
    * no confirmation of form submission
* petition system or hack on email subscription list (e.g. sendinblue)
  * Options: https://civist.com/
  * allows for submission confirmation (via email)
  * allows for tracking counts of signatories

[maybe-not]: https://blog.webjeda.com/google-form-customize/

### WP petition research

https://civist.com - looks ok
http://wppetitions.com - so-so
https://wordpress.org/plugins/speakout/ - looks a bit old (?)

https://wings.dev - kind of what we want for the future but is proprietary afaict (built on gatsby?)

---

### Temporarily solution

* form embedded on website as <iframe>

![temporaryform](/uploads/03fe00a6c009e9ff133774c0c024a16a/temporaryform.png)

### Best solution

* form translated to vue.js and integrated as a component 

## New form looks

![new_form_possibility](/uploads/fcee317a7ef9808b93db48ab3e333fb7/new_form_possibility.png)

## How to update endorsers list 

added instructions to the README.md of the website. See screenshot below.

![endorsers_list_instructions](/uploads/c32acb2bdf35e1ac0729fc3395fa7687/endorsers_list_instructions.png)

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 18:16

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 18:39

changed title from **{-Form endorse flow rather than email-}** to **{+[epic] Form endorse flow rather than email plus display total and names on website+}**

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 20:53

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 6, 2020, 21:08

@monikappv can you update on where you are at with this with a bit of detail (and can you start updating daily (assuming you have worked on it).

PS: you might want to quickly (~1h) check out sendgrid - https://sendgrid.com - just sign up and see if you can create a form that you can embed (even as an iframe).

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 7, 2020, 19:42

marked the task **choose the form system** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 7, 2020, 19:42

marked the task **What are our needs?** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 7, 2020, 19:42

marked the task **Research options** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 7, 2020, 19:42

marked the task **Choose one and try it** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 7, 2020, 19:43

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 7, 2020, 19:43

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 7, 2020, 19:50

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 7, 2020, 20:03

@rufuspollock integrated the form with iframe for now, tested and deployed it - it works. 
also researched the sendgrid.com and tried to build a form with it --> i think it is worse than sendinblue in terms of user experience, customization options and ways of sharing. I will add more details to the description..

## Rufus coaching on how to do this even better

Some remaining things:

* I've left the email sign up option - but probably you want me to remove? If yes, let me know.
* More importantly after sign up you go to this ugly page:

INSERT Screenshot

Here is what we can do ...

* A
* B
* C

I recommend A. I will implement this unless i hear from you by X time.

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 8, 2020, 17:52

marked the task **Sign up form working** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 8, 2020, 18:34

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 10, 2020, 19:21

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 13, 2020, 20:09

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 13, 2020, 20:10

marked the task **improve confirmation page** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 13, 2020, 20:10

marked the task **Use data from form to show list of endorsers etc** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 13, 2020, 20:10

marked the task **Display total** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 13, 2020, 20:10

marked the task **Display names and orgs (if happy to be public)** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 13, 2020, 20:13

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 13, 2020, 20:18

changed time estimate to 1d

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 13, 2020, 20:19

added 1d 4h of time spent at 2020-05-13

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on Jun 1, 2020, 19:02

marked the task **improve form (translate to vue.js and embed as a component instead of using iframe)** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on Jun 1, 2020, 19:02

marked the task **replace token with variable** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on Jun 1, 2020, 19:04

closed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on Jun 15, 2020, 16:28

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on Jun 15, 2020, 17:06

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on Jun 15, 2020, 17:06

marked the task **Document this for others** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on Jun 15, 2020, 17:08

FIXED.

The form has been improved (see photo in issue description).
Also added a section in the repo README.md with instructions on how to update the endorsers list.

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on Jun 15, 2020, 17:08

reopened

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on Jun 15, 2020, 17:08

closed
