### ISSUE TITLE
Create Possibility Now facebook page (or group)?

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#4]
In GitLab by @rufuspollock on Apr 15, 2020, 18:29

## Tasks

* [x] Work out whether we want a group or a page or both **Group.**
* [x] Create them  **See here: https://www.facebook.com/groups/237565060693847/**
* [ ] Add key people to admin e.g. alistair, sylvie, sophie, petronella

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 18:54

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 18:55

changed title from **Create Possibility Now facebook page** to **Create Possibility Now facebook page{+ (or group)?+}**

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 18:55

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 19:09

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 19:09

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 16, 2020, 19:10

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 17, 2020, 18:27

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 19, 2020, 09:42

FIXED. Sylvie add Sophie, Georgia and Jacques as admins.

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 19, 2020, 09:42

closed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 21, 2020, 19:09

reopened

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 21, 2020, 19:11

@shiweiart Georgia and I don't seem to be admins yet

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 29, 2020, 18:38

FIXED. 😄 All are admins.

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Apr 29, 2020, 18:38

closed
