### ISSUE TITLE
[site] Directory page showing orgs and initiatives from spreadsheet

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#40]
In GitLab by @rufuspollock on May 3, 2020, 20:58

When visiting possibility now I want know about other initiatives and groups so that I can get in touch with them

Will be from this spreadsheet which can be made public https://docs.google.com/spreadsheets/d/1QJpTHWr9RKZGFaKjIR6itpQqQlGJNfXmoR8nFw-72EU/edit#gid=281905530

Can reuse learnings from https://gitlab.com/datopian/tech/breakable-toys/-/issues/8

## Acceptance

* [x] `/directory/` page listing of initiatives and orgs with "card" like layout - see https://tailwindcss.com/components/cards/ (probably horizontal is better but i'm not sure)
* [x] Show title, description, url, image, type, hashtag --> **no type defined in spreadsheet**
  * [x] Use a nice placeholder image from unsplash if no image url provided

## Tasks

* [x] apply learnings from https://gitlab.com/datopian/tech/breakable-toys/-/issues/8
  * [x] build right API path to spreadsheet
    * [x] get spreadsheetId
    * [x] research how to get the wanted range and sheet tab
    * [x] generate API key
    * [x] consolidate into one API path 
  * [x] install axios 
  * [x] add Directory.vue component containing the axios script and the consolidated API path to spreadsheet
* [x] create directory folder and README.md and add layout and title setting
* [x] register component in Layout.vue
* [x] test if it works
* [x] copy tailwind card layout https://tailwindcss.com/components/cards/ and adjust to the directory listing
* [x] screenshot home pages of first 4 websites, upload in imgur and use as cards images
* [x] find some cool image in unsplash.com as fallback for the others that I haven't screenshotted yet 
* [x] add v-if statements where needed to avoid showing cards with empty titles / hashtags
* [x] deploy
* [x] make screenshots of the rest of the sites and paste url in the spreadsheet
* [x] polish off
 
NB: screenshot home pages of websites and paste in imgur.com to get the url

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 3, 2020, 20:59

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 4, 2020, 08:59

assigned to @monikappv

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 8, 2020, 18:37

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 8, 2020, 18:43

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 8, 2020, 18:44

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on May 10, 2020, 19:22

@monikappv had a thought here - to start with you could just hard code the top three in the page so we can see what it looks like b4 we get all fancy and wire it up.

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 11, 2020, 16:21

@rufuspollock i was pretty close to implementing it dynamically so there was no need to hard code - I did it the way we discussed (with the cards layout) for now, we can then iterate.. here is a screenshot

![directory_listing_screenshot](/uploads/c6d3956e8572585d1ddcb34930852e21/directory_listing_screenshot.png)

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 11, 2020, 16:22

changed time estimate to 4h

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 11, 2020, 16:23

added 4h of time spent at 2020-05-11

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 11, 2020, 16:39

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 11, 2020, 16:41

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 11, 2020, 16:42

marked the task **Use a nice placeholder image from unsplash if no image url provided** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 11, 2020, 16:42

marked the task **`/directory/` page listing of initiatives and orgs with "card" like layout - see https://tailwindcss.com/components/cards/ (probably horizontal is better but i'm not sure)** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 11, 2020, 16:42

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 11, 2020, 16:43

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 11, 2020, 18:45

marked the task **make screenshots of the rest of the sites and paste url in the spreadsheet** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 11, 2020, 18:58

FIXED. 

NB: directory listing gets updated on refresh if you update the DB / spreadsheet.

see screenshot https://gitlab.com/artearthtech/possibility-now/-/issues/40#note_340260780 or live on https://possibilitynow.org/directory/.

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 11, 2020, 18:58

closed
