### ISSUE TITLE
Draft Email you get upon endorsing

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#43]
In GitLab by @rufuspollock on May 8, 2020, 18:19

When I endorse I want to get a confirmation email including next steps as well as going to the endorsed page so that I have a permanent record (plus I know if someone abused my email and submitted me). [It could also be useful if we want to do double opt-in]

## Tasks

* [ ] Do we want one?
* [ ] Who is it from? possibilitynow@artearthtech.com
* [ ] What does it say?
