### ISSUE TITLE
Put new logo on the website

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#46]
In GitLab by @monikappv on May 18, 2020, 19:26

![possibility-now-logo-square](/uploads/c0bdfc4968aa1441d96cb681dfd1a0d3/possibility-now-logo-square.png)

## Acceptance

* [x] new logo is live on the website
* [x] in SVG format

## Tasks

* [x] get all logo elements from Katrien - yellow paint png, font details
* [x] remove background from yellow paint png
* [x] get font details
* [x] put the logo together based on the given elements so that we can 1. change the font and 2. have it in SVG format
* [x] place on navbar
* [x] adjust accordingly
* [x] deploy

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 18, 2020, 19:27

changed time estimate to 1h

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 18, 2020, 19:27

added 1h of time spent at 2020-05-18

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 18, 2020, 19:46

marked the task **new logo is live on the website** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 18, 2020, 19:46

marked the task **in SVG format** as completed

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 18, 2020, 19:48

FIXED. 

New logo is live on the website 
![possibility-now-screenshot](/uploads/ba22bb6f784cfc1237a08b1100346647/possibility-now-screenshot.png)

**Comment by rufuspollock** [comment]
In GitLab by @monikappv on May 18, 2020, 19:48

closed
