### ISSUE TITLE
Possibility Now Betterment Commons - writing examples for directory

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#48]
In GitLab by @shiweiart on Jun 9, 2020, 20:41

Sub-issue of https://gitlab.com/lifeitself/pm/-/issues/403

Betterment Commons text: https://docs.google.com/document/d/1hYpfcogKxM_KsOqhvuR1HrI1vQ9IJw-yrl9UreagxAA/edit

Example of spreadsheet: https://docs.google.com/spreadsheets/d/1QJpTHWr9RKZGFaKjIR6itpQqQlGJNfXmoR8nFw-72EU/edit#gid=0

Principles underpining Betterment Commons: https://docs.google.com/document/d/1rmxMlbiXEyAHy4fSACTghMLpKBvhmMYWWSap-H0pksg/edit

Betterment Commons Submission Form: https://docs.google.com/forms/u/2/d/1rAbu8qh4DmKb4cKfD9fUYKHVQ9BFV6ui_CSJpA6nAP4/edit?usp=drive_web

## Acceptance

* [x] Examples for directory have been reviewed by Sylvie **Sophie - Sylvie said she'd looked at the spreadsheet, so think it's been reviewed**

## Tasks
* [ ] put sylvie covid video on youtube channel ( it's on rufus Zoom)
* [x] read sylvie let's get political - here https://docs.google.com/document/d/1rmxMlbiXEyAHy4fSACTghMLpKBvhmMYWWSap-H0pksg/edit
* [x] correct of improve text of the bettermen commons - here https://docs.google.com/document/d/1hYpfcogKxM_KsOqhvuR1HrI1vQ9IJw-yrl9UreagxAA/edit
* [x] create a soreadsheet of bettermen commons **see here: https://docs.google.com/spreadsheets/d/1Q_HuthywEwf1aLIBtxnRUBI2_BQfOLy6zEyeAqnqKgc/edit#gid=0**
* [x] put in the sheet a database of bettermen commons that you believe is worth the attention, based on the principles here - https://docs.google.com/document/d/1rmxMlbiXEyAHy4fSACTghMLpKBvhmMYWWSap-H0pksg/edit# write about 3 sentences to start, explaining the initiative/intervention/policy etc... 
* [x] have a short list of 5 of them
* [x] have sylvie review them

**Comment by rufuspollock** [comment]
In GitLab by @shiweiart on Jun 9, 2020, 20:42

assigned to @rufuspollock

**Comment by rufuspollock** [comment]
In GitLab by @shiweiart on Jun 9, 2020, 20:43

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @shiweiart on Jun 10, 2020, 16:46

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @shiweiart on Jun 10, 2020, 16:49

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @shiweiart on Jun 10, 2020, 17:08


name of initiative
Organisation: 
Link: 
Topic areas: e.g. health, community, economy, networks, ecology, theory...
Scale: local, bioregion, country, international, global?
Community: house, street, neighbourhood, city, region, national, global
Status: idea, prototype, plug-and-play

**Comment by rufuspollock** [comment]
In GitLab by @shiweiart on Jun 10, 2020, 17:13

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Jun 29, 2020, 15:34

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Jun 29, 2020, 15:36

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Jun 29, 2020, 15:37

changed the description

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Jun 30, 2020, 12:09

marked the task **read sylvie let's get political - here https://docs.google.com/document/d/1rmxMlbiXEyAHy4fSACTghMLpKBvhmMYWWSap-H0pksg/edit** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Jul 3, 2020, 09:38

marked the task **create a soreadsheet of bettermen commons **see here: https://docs.google.com/spreadsheets/d/1Q_HuthywEwf1aLIBtxnRUBI2_BQfOLy6zEyeAqnqKgc/edit#gid=0**** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Jul 6, 2020, 15:24

marked the task **put in the sheet a database of bettermen commons that you believe is worth the attention, based on the principles here - https://docs.google.com/document/d/1rmxMlbiXEyAHy4fSACTghMLpKBvhmMYWWSap-H0pksg/edit# write about 3 sentences to start, explaining the initiative/intervention/policy etc...** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Jul 6, 2020, 15:24

marked the task **have a short list of 5 of them** as completed

**Comment by rufuspollock** [comment]
In GitLab by @WillM30 on Jul 9, 2020, 16:00

@rufuspollock I reviewed up to where you said stop

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Jul 9, 2020, 17:26

really appreciate it, thanks! :)

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Jul 9, 2020, 17:28

marked the task **correct of improve text of the bettermen commons - here https://docs.google.com/document/d/1hYpfcogKxM_KsOqhvuR1HrI1vQ9IJw-yrl9UreagxAA/edit** as completed

**Comment by rufuspollock** [comment]
In GitLab by @rufuspollock on Jul 13, 2020, 17:28

@shiweiart Sylvie just checking you haven't forgotten about reviewing these? https://docs.google.com/spreadsheets/d/1QJpTHWr9RKZGFaKjIR6itpQqQlGJNfXmoR8nFw-72EU/edit#gid=0 Know you're busy!
