### ISSUE TITLE
Possibility Now Betterment Commons - creating page and directory

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/possibility-now#49]
We want to put a page about the betterment common with so that we appropriate this idea and are known for that

draft of betterment common text: https://docs.google.com/document/u/2/d/1hYpfcogKxM_KsOqhvuR1HrI1vQ9IJw-yrl9UreagxAA/edit?usp=drive_web&ouid=117157573293978592624

Form to submit betterment commons: https://docs.google.com/forms/u/2/d/1rAbu8qh4DmKb4cKfD9fUYKHVQ9BFV6ui_CSJpA6nAP4/edit?usp=drive_web

## Acceptance

* [ ] betterment commons page up on the possibility now website
* [ ] directory up on the possibility now website

## Tasks

* [x] draft text of the betterment commons
* [x] task sophie or william to create a spreadsheet of betterment commons and Sylvie to review **DONE**
* [ ] create a page by monika
* [ ] put the text up
* [ ] create a directory of the bettermen commons
